/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.praktek;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class laundry extends javax.swing.JInternalFrame {

    KoneksiDB konek = new KoneksiDB();
    DefaultTableModel tabModel;
    String jenis, kode, hargabaju;

    public laundry() {
        initComponents();
        kode();
        data();
    }

    void kode() {
        try {
            konek.query = "select MAX(right(kode_baju, 1)) as kode from laundry";
            konek.getData();
            while (konek.result.next()) {
                if (konek.result.first() == false) {
                    kodebaju.setText("1");
                } else {
                    konek.result.last();

                    int id = konek.result.getInt(1) + 1;

                    String no = String.valueOf(id);

                    kodebaju.setText(no);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void data() {
        try {
            tabModel = (DefaultTableModel) tabellaundry.getModel();
            tabModel.getDataVector().removeAllElements();
            revalidate();

            konek.query = "select * from laundry";
            konek.getData();

            while (konek.result.next()) {
                kode = konek.result.getString(1);
                jenis = konek.result.getString(2);
                hargabaju = konek.result.getString(3);

                String[] data = {kode, jenis, hargabaju};
                tabModel.addRow(data);
            }
        } catch (SQLException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kering = new javax.swing.JRadioButton();
        basah = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        kodebaju = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellaundry = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("laundry");

        jLabel1.setText("Jenis Baju");

        buttonGroup1.add(kering);
        kering.setText("Kering");

        buttonGroup1.add(basah);
        basah.setText("Basah");

        jLabel2.setText("Kode Baju");

        kodebaju.setEditable(false);

        jLabel3.setText("Harga");

        harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hargaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaKeyTyped(evt);
            }
        });

        edit.setText("EDIT");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        simpan.setText("SIMPAN");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        tabellaundry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Jenis"
            }
        ));
        tabellaundry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellaundryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabellaundry);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(kering)
                        .addGap(26, 26, 26)
                        .addComponent(basah))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kodebaju)
                            .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit)
                        .addGap(49, 49, 49)
                        .addComponent(hapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kering)
                        .addComponent(basah))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kodebaju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpan)
                    .addComponent(edit)
                    .addComponent(hapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        String jenisbaju = null;
        if (harga.getText().equals("") || (!kering.isSelected() && !basah.isSelected())) {

        } else {
            try {
                konek.query = "insert into laundry values (?,?,?)";
                konek.setData();
                konek.preparedstatement.setInt(1, Integer.parseInt(kodebaju.getText()));
                if (kering.isSelected()) {
                    jenisbaju = kering.getText();
                } else if (basah.isSelected()) {
                    jenisbaju = basah.getText();
                }
                konek.preparedstatement.setString(2, jenisbaju);
                konek.preparedstatement.setString(3, harga.getText());
                konek.preparedstatement.executeUpdate();
                data();
                clear();
                kode();
            } catch (SQLException ex) {
                Logger.getLogger(laundry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_simpanMouseClicked

    private void tabellaundryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellaundryMouseClicked
        int rowIndex = tabellaundry.getSelectedRow();

        kodebaju.setText((String) tabellaundry.getValueAt(rowIndex, 0));
        int kodelaun = Integer.parseInt(kodebaju.getText());

        try {
            konek.query = "select * from laundry where kode_baju = '" + kodelaun + "'";
            konek.getData();
            if (konek.result.next()) {
                kode = konek.result.getString(1);
                jenis = konek.result.getString(2);
                hargabaju = konek.result.getString(3);
            }

        } catch (SQLException ex) {

        }

        harga.setText(hargabaju);

        if (jenis.equals("Kering")) {
            kering.setSelected(true);
        } else {
            basah.setSelected(true);
        }

    }//GEN-LAST:event_tabellaundryMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Kamu yakin mau menghapus data " + kodebaju.getText() + " ?", "Waring", JOptionPane.YES_NO_OPTION);

        int kodelaun = Integer.parseInt(kodebaju.getText());

        if (a == JOptionPane.YES_OPTION) {
            try {
                konek.query = "delete from laundry where kode_baju = '" + kodelaun + "'";
                konek.setData();
                konek.preparedstatement.executeUpdate();
                clear();
                data();
                
            } catch (SQLException ex) {
            }
        } else {

        }
    }//GEN-LAST:event_hapusMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        int kodelaun = Integer.parseInt(kodebaju.getText());
        String jenisbaju = null;
        if (harga.getText().equals("") || (!kering.isSelected() && !basah.isSelected())) {

        } else {
            try {
                konek.query = "update laundry set kode_baju = ?, jenis_baju = ?, harga = ? where kode_baju = '" + kodelaun + "'";
                konek.setData();
                konek.preparedstatement.setInt(1, Integer.parseInt(kodebaju.getText()));

                if (kering.isSelected()) {
                    jenisbaju = kering.getText();
                } else if (basah.isSelected()) {
                    jenisbaju = basah.getText();
                }
                konek.preparedstatement.setString(2, jenisbaju);
                konek.preparedstatement.setString(3, harga.getText());
                konek.preparedstatement.executeUpdate();
                clear();
                data();
                kode();
            } catch (SQLException ex) {
                Logger.getLogger(laundry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_editMouseClicked

    private void hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaKeyPressed

    private void hargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "Inputkan Angka Saja", "info", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_hargaKeyTyped

    void clear() {
        buttonGroup1.clearSelection();
        harga.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton basah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton kering;
    private javax.swing.JTextField kodebaju;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabellaundry;
    // End of variables declaration//GEN-END:variables
}
