/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.praktek;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class pelanggan extends javax.swing.JInternalFrame {

    KoneksiDB konek = new KoneksiDB();
    DefaultTableModel tabModel;
    String nama, alamatpel, kode, nohppel;

    public pelanggan() {
        initComponents();
        kode();
        data();
    }

    void kode() {
        try {
            konek.query = "select MAX(right(kode_pelanggan, 1)) as kode from pelanggan";
            konek.getData();
            while (konek.result.next()) {
                if (konek.result.first() == false) {
                    kodepelanggan.setText("1");
                } else {
                    konek.result.last();

                    int id = konek.result.getInt(1) + 1;

                    String no = String.valueOf(id);

                    kodepelanggan.setText(no);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void data() {
        try {
            tabModel = (DefaultTableModel) tabelpelanggan.getModel();
            tabModel.getDataVector().removeAllElements();
            revalidate();

            konek.query = "select * from pelanggan";
            konek.getData();

            while (konek.result.next()) {
                kode = konek.result.getString(1);
                nama = konek.result.getString(2);
                alamatpel = konek.result.getString(3);
                nohppel = konek.result.getString(4);

                String[] data = {kode, nama, alamatpel, nohppel};
                tabModel.addRow(data);
            }
        } catch (SQLException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kodepelanggan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namapelanggan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpelanggan = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("pelanggan");

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setText("Kode Pelanggan");

        kodepelanggan.setEditable(false);

        jLabel2.setText("Nama Pelanggan");

        namapelanggan.setToolTipText("");
        namapelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namapelangganKeyTyped(evt);
            }
        });

        jLabel3.setText("Alamat");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jLabel4.setText("No HP");

        nohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nohpKeyTyped(evt);
            }
        });

        simpan.setText("SIMPAN");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });

        edit.setText("EDIT");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        tabelpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama"
            }
        ));
        tabelpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelpelanggan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(simpan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(edit)
                                .addGap(49, 49, 49)
                                .addComponent(hapus))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(kodepelanggan)
                                .addComponent(namapelanggan)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                .addComponent(nohp)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kodepelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(namapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpan)
                    .addComponent(edit)
                    .addComponent(hapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        if (kodepelanggan.getText().equals("") || namapelanggan.getText().equals("") || alamat.getText().equals("") || nohp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "belum benar", "info", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                konek.query = "insert into pelanggan values(?,?,?,?)";
                konek.setData();
                konek.preparedstatement.setInt(1, Integer.parseInt(kodepelanggan.getText()));
                konek.preparedstatement.setString(2, namapelanggan.getText());
                konek.preparedstatement.setString(3, alamat.getText());
                konek.preparedstatement.setString(4, nohp.getText());

                konek.preparedstatement.executeUpdate();
                data();
                clear();
                kode();
            } catch (SQLException ex) {
                Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_simpanMouseClicked

    private void nohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nohpKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "Inputkan Angka Saja", "info", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_nohpKeyTyped

    private void tabelpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpelangganMouseClicked
        int rowIndex = tabelpelanggan.getSelectedRow();

        kodepelanggan.setText((String) tabelpelanggan.getValueAt(rowIndex, 0));
        int kodepel = Integer.parseInt(kodepelanggan.getText());

        try {
            konek.query = "select * from pelanggan where kode_pelanggan = '" + kodepel + "'";
            konek.getData();
            if (konek.result.next()) {
                kode = konek.result.getString(1);
                nama = konek.result.getString(2);
                alamatpel = konek.result.getString(3);
                nohppel = konek.result.getString(4);
            }

        } catch (SQLException ex) {

        }

        namapelanggan.setText(nama);
        alamat.setText(alamatpel);
        nohp.setText(nohppel);
    }//GEN-LAST:event_tabelpelangganMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Kamu yakin mau menghapus data " + namapelanggan.getText() + " ?", "Waring", JOptionPane.YES_NO_OPTION);

        int kodepel = Integer.parseInt(kodepelanggan.getText());

        if (a == JOptionPane.YES_OPTION) {
            try {
                konek.query = "delete from pelanggan where kode_pelanggan = '" + kodepel + "'";
                konek.setData();
                konek.preparedstatement.executeUpdate();
                clear();
                data();
            } catch (SQLException ex) {
            }
        } else {

        }
    }//GEN-LAST:event_hapusMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        int kodepel = Integer.parseInt(kodepelanggan.getText());
        if (kodepelanggan.getText().equals("") || namapelanggan.getText().equals("") || alamat.getText().equals("") || nohp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "belum benar", "info", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                konek.query = "update pelanggan set kode_pelanggan = ?, nama_pelanggan = ?, alamat = ?, nohp = ? where kode_pelanggan = '" + kodepel + "'";
                konek.setData();
                konek.preparedstatement.setInt(1, Integer.parseInt(kodepelanggan.getText()));
                konek.preparedstatement.setString(2, namapelanggan.getText());
                konek.preparedstatement.setString(3, alamat.getText());
                konek.preparedstatement.setString(4, nohp.getText());

                konek.preparedstatement.executeUpdate();
                data();
                clear();
                kode();
            } catch (SQLException ex) {
                Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_editMouseClicked

    private void namapelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namapelangganKeyTyped

    }//GEN-LAST:event_namapelangganKeyTyped

    void clear() {
        namapelanggan.setText("");
        alamat.setText("");
        nohp.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kodepelanggan;
    private javax.swing.JTextField namapelanggan;
    private javax.swing.JTextField nohp;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelpelanggan;
    // End of variables declaration//GEN-END:variables
}
