/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.praktek;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class transaksi extends javax.swing.JInternalFrame {

    KoneksiDB konek = new KoneksiDB();
    String nama, alamatpel, kode, nohppel, kodebaju;

    public transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kodepelanggan = new javax.swing.JTextField();
        namapelanggan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kering = new javax.swing.JRadioButton();
        basah = new javax.swing.JRadioButton();
        hargabaju = new javax.swing.JLabel();
        beratbaju = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        submit = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Transaksi");

        jLabel1.setText("Kode pelanggan");

        kodepelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodepelangganActionPerformed(evt);
            }
        });
        kodepelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kodepelangganKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kodepelangganKeyTyped(evt);
            }
        });

        namapelanggan.setText("null");

        jLabel2.setText("Transaksi");

        jLabel3.setText("Jenis baju");

        jLabel4.setText("Harga");

        jLabel5.setText("Berat baju");

        jLabel6.setText("Total");

        buttonGroup1.add(kering);
        kering.setText("kering");
        kering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keringActionPerformed(evt);
            }
        });

        buttonGroup1.add(basah);
        basah.setText("Basah");
        basah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basahActionPerformed(evt);
            }
        });

        hargabaju.setText("null");

        beratbaju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratbajuActionPerformed(evt);
            }
        });
        beratbaju.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beratbajuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                beratbajuKeyTyped(evt);
            }
        });

        total.setText("null");

        submit.setText("Submit");
        submit.setToolTipText("");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hargabaju)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(kering)
                                    .addGap(18, 18, 18)
                                    .addComponent(basah))
                                .addComponent(namapelanggan)
                                .addComponent(kodepelanggan)
                                .addComponent(beratbaju, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))))
                    .addComponent(submit))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kodepelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(namapelanggan)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kering)
                    .addComponent(basah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hargabaju))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(beratbaju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodepelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodepelangganActionPerformed
        int kodepel = Integer.parseInt(kodepelanggan.getText());

        try {
            konek.query = "select * from pelanggan where kode_pelanggan = '" + kodepel + "'";
            konek.getData();
            if (konek.result.next()) {
                kode = konek.result.getString(1);
                nama = konek.result.getString(2);
                alamatpel = konek.result.getString(3);
                nohppel = konek.result.getString(4);
                namapelanggan.setText(nama);
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada", "info", JOptionPane.INFORMATION_MESSAGE);
                namapelanggan.setText("null");
            }

        } catch (SQLException ex) {

        }


    }//GEN-LAST:event_kodepelangganActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        if (namapelanggan.getText().equals("null") || beratbaju.getText().equals("") || (!kering.isSelected() && !basah.isSelected())) {

        } else {
            try {
                konek.query = "insert into transaksi values (?,?,?,?)";
                konek.setData();
                konek.preparedstatement.setInt(1, Integer.parseInt(kode));
                konek.preparedstatement.setInt(2, Integer.parseInt(kodebaju));
                konek.preparedstatement.setString(3, beratbaju.getText());
                konek.preparedstatement.setString(4, total.getText());
                konek.preparedstatement.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
            }

            String jenisbaju;

            if (kering.isSelected()) {
                jenisbaju = "Kering";
            } else {
                jenisbaju = "Basah";
            }

            JOptionPane.showMessageDialog(null, "Nama : " + namapelanggan.getText() + "\n" + "Jenis baju : " + jenisbaju + "\n" + "Berat baju : " + beratbaju.getText() + "\n" + "Total : " + total.getText(), "info", JOptionPane.INFORMATION_MESSAGE);
            clear();
        }
    }//GEN-LAST:event_submitMouseClicked

    private void keringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keringActionPerformed
        try {
            konek.query = "select * from laundry where jenis_baju = '" + kering.getText() + "'";
            konek.getData();
            if (konek.result.next()) {
                kodebaju = konek.result.getString(1);
                hargabaju.setText(konek.result.getString(3));
            }

        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_keringActionPerformed

    private void basahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basahActionPerformed
        try {
            konek.query = "select * from laundry where jenis_baju = '" + basah.getText() + "'";
            konek.getData();
            if (konek.result.next()) {
                kodebaju = konek.result.getString(1);
                hargabaju.setText(konek.result.getString(3));
            }

        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_basahActionPerformed

    private void beratbajuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beratbajuKeyReleased

    }//GEN-LAST:event_beratbajuKeyReleased

    private void beratbajuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beratbajuKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "Inputkan Angka Saja", "info", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_beratbajuKeyTyped

    private void kodepelangganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodepelangganKeyReleased

    }//GEN-LAST:event_kodepelangganKeyReleased

    private void kodepelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodepelangganKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "Inputkan Angka Saja", "info", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_kodepelangganKeyTyped

    private void beratbajuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratbajuActionPerformed
        int harga = Integer.parseInt(hargabaju.getText());
        int berat = Integer.parseInt(beratbaju.getText());
        int totalharga = harga * berat;
        total.setText(String.valueOf(totalharga));
    }//GEN-LAST:event_beratbajuActionPerformed

    void clear() {
        kodepelanggan.setText("");
        namapelanggan.setText("null");
        buttonGroup1.clearSelection();
        hargabaju.setText("null");
        beratbaju.setText("");
        total.setText("null");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton basah;
    private javax.swing.JTextField beratbaju;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hargabaju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton kering;
    private javax.swing.JTextField kodepelanggan;
    private javax.swing.JLabel namapelanggan;
    private javax.swing.JButton submit;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
